// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0XK4Lc3vEjXihJzpOkJoqsRcy5S4bWTc',
    appId: '1:507548881380:web:f1be00dbc2b2ab304eb7f1',
    messagingSenderId: '507548881380',
    projectId: 'home-workout-eee57',
    authDomain: 'home-workout-eee57.firebaseapp.com',
    storageBucket: 'home-workout-eee57.appspot.com',
    measurementId: 'G-3ZFCYVRFZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUPxjM81l_8nXe3MDbbEo0WnsFs2XjQws',
    appId: '1:507548881380:android:9ede41ed3572290b4eb7f1',
    messagingSenderId: '507548881380',
    projectId: 'home-workout-eee57',
    storageBucket: 'home-workout-eee57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU093QBiPzmuR_XIkkrDSp3GyEi6W5iZU',
    appId: '1:507548881380:ios:6f0a5997bee7537a4eb7f1',
    messagingSenderId: '507548881380',
    projectId: 'home-workout-eee57',
    storageBucket: 'home-workout-eee57.appspot.com',
    iosBundleId: 'com.example.homeworkout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU093QBiPzmuR_XIkkrDSp3GyEi6W5iZU',
    appId: '1:507548881380:ios:9fddd1f9e559d6f54eb7f1',
    messagingSenderId: '507548881380',
    projectId: 'home-workout-eee57',
    storageBucket: 'home-workout-eee57.appspot.com',
    iosBundleId: 'com.example.homeworkout.RunnerTests',
  );
}
